version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${DB_ADMIN_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_ADMIN_PASS}
  postgres:
    image: "postgres:17-alpine3.21"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_ADMIN_USER}
      - POSTGRES_PASSWORD=${DB_ADMIN_PASS}
      - POSTGRES_DB=${DB_DATABASE}
    restart: unless-stopped